/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bonecos.kuscos.factory;

import java.sql.Connection;
import com.bonecos.kuscos.dao.*;
import com.bonecos.kuscos.jdbc.*;

public class ClientesbonecosDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return ClientesbonecosDao
	 */
	public static ClientesbonecosDao create()
	{
		return new ClientesbonecosDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return ClientesbonecosDao
	 */
	public static ClientesbonecosDao create(Connection conn)
	{
		return new ClientesbonecosDaoImpl( conn );
	}

}
