/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bonecos.kusco.j2ee.session;

import com.bonecos.kusco.factory.*;
import com.bonecos.kusco.dao.*;
import com.bonecos.kusco.dto.*;
import com.bonecos.kusco.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;

public interface ClientesbonecosSession
{
	/** 
	 * Inserts a new row in the CLIENTESBONECOS table.
	 */
	public ClientesbonecosPk insert(Clientesbonecos dto) throws ClientesbonecosDaoException, RemoteException;

	/** 
	 * Updates a single row in the CLIENTESBONECOS table.
	 */
	public void update(ClientesbonecosPk pk, Clientesbonecos dto) throws ClientesbonecosDaoException, RemoteException;

	/** 
	 * Deletes a single row in the CLIENTESBONECOS table.
	 */
	public void delete(ClientesbonecosPk pk) throws ClientesbonecosDaoException, RemoteException;

	/** 
	 * Returns the rows from the CLIENTESBONECOS table that matches the specified primary-key value.
	 */
	public Clientesbonecos findByPrimaryKey(ClientesbonecosPk pk) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param idCliente
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos
	 */
	public Clientesbonecos findByPrimaryKey(long idCliente) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findAll'
	 * 
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findAll() throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereIdClienteEquals'
	 * 
	 * @param idCliente
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereIdClienteEquals(long idCliente) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereNumeroCcEquals'
	 * 
	 * @param numeroCc
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereNumeroCcEquals(long numeroCc) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereNomeEquals'
	 * 
	 * @param nome
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereNomeEquals(String nome) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereMoradaEquals'
	 * 
	 * @param morada
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereMoradaEquals(String morada) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereDataNascimentoEquals'
	 * 
	 * @param dataNascimento
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereDataNascimentoEquals(Date dataNascimento) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereDataInsercaoEquals'
	 * 
	 * @param dataInsercao
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereDataInsercaoEquals(Date dataInsercao) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findWhereGeneroEquals'
	 * 
	 * @param genero
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findWhereGeneroEquals(String genero) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findByDynamicSelect(String sql, Object[] arg) throws ClientesbonecosDaoException, RemoteException;

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ClientesbonecosDaoException
	 * @throws RemoteException
	 * @return Clientesbonecos[]
	 */
	public Clientesbonecos[] findByDynamicWhere(String sql, Object[] arg) throws ClientesbonecosDaoException, RemoteException;

}
